local colors = require("ui.themer").colorscheme("vivid")
return {
  Comment = { fg = colors.dark.black25, italic = true },
  Conceal = { bg = "NONE" },
  ColorColumn = { bg = colors.dark.black05, sp = "none" },
  CursorColumn = { bg = colors.dark.black05, sp = "none" },
  Cursor = { fg = colors.black, bg = colors.dark.black25 },
  iCursor = { fg = colors.black, bg = colors.dark.black25 },
  CursorLine = { bg = colors.dark.black05, sp = "none" },
  CursorLineNr = { fg = colors.white },
  Debug = { fg = colors.cyan },
  Directory = { fg = colors.blue },
  FloatBorder = { fg = colors.dark.black90, bg = colors.black },
  NormalFloat = { bg = colors.black },
  NvimInternalError = { fg = colors.error },
  WinSeparator = { fg = colors.dark.black15 },
  Bold = { bold = true },
  Italic = { italic = true },
  UnderLined = { fg = colors.green },
  Error = { fg = colors.black, bg = colors.error },
  ErrorMsg = { fg = colors.error, bg = colors.black },
  Exception = { fg = colors.error },
  FoldColumn = { fg = colors.cyan, bg = colors.dark.black05 },
  Folded = { fg = colors.dark.black15, bg = colors.dark.black05 },
  healthSuccess = { fg = colors.black, bg = colors.green },
  IncSearch = { fg = colors.black, bg = colors.orange },
  LineNr = { fg = colors.dark.black15 },
  Macro = { fg = colors.red },
  MatchWord = { bg = colors.dark.black15, fg = colors.white },
  MatchParen = { link = "MatchWord" },
  ModeMsg = { fg = colors.green },
  MoreMsg = { fg = colors.green },
  NonText = { fg = colors.dark.black25 },
  Normal = { fg = colors.light.white05, bg = colors.black },
  Pmenu = { bg = colors.dark.black10 },
  PmenuSbar = { bg = colors.dark.black10 },
  PmenuSel = { bg = colors.dark.black25 },
  PmenuThumb = { bg = colors.dark.black15 },
  Question = { fg = colors.blue },
  QuickFixLine = { bg = colors.dark.black05, sp = "none" },
  Search = { fg = colors.dark.black05, bg = colors.yellow },
  SignColumn = { fg = colors.dark.black15, sp = "NONE" },
  SpecialKey = { fg = colors.dark.black15 },
  SpellBad = { undercurl = true, sp = colors.error },
  SpellLocal = { undercurl = true, sp = colors.cyan },
  SpellCap = { undercurl = true, sp = colors.blue },
  SpellRare = { undercurl = true, sp = colors.magenta },
  Substitute = { fg = colors.dark.black05, bg = colors.yellow, sp = "none" },
  Statement = { fg = colors.red },
  Title = { fg = colors.blue, sp = "none" },
  TooLong = { fg = colors.error },
  Visual = { bg = colors.dark.black10 },
  VisualNOS = { fg = colors.error },
  WarningMsg = { fg = colors.yellow },
  WildMenu = { fg = colors.red, bg = colors.yellow },

  DiagnosticError = { fg = colors.error },
  DiagnosticWarn = { fg = colors.orange },
  DiagnosticInfo = { fg = colors.green },
  DiagnosticHint = { fg = colors.magenta },
}
