local colors = require("ui.themer").colorscheme("vivid")

return {
  CmpItemAbbr = { fg = colors.white },
  CmpItemAbbrDeprecated = { fg = colors.dark.black10, strikethrough = true },
  CmpItemAbbrMatch = { fg = colors.blue, bold = true },
  CmpDocBorder = { fg = colors.dark.black10, bg = colors.dark.black10 },
  CmpItemMenu = { fg = colors.white, bg = colors.dark.black10 },
  CmpPmenu = { bg = colors.dark.black10 },
  CmpPmenuBorder = { bg = colors.dark.black10 },
  CmpItemKindConstant = { fg = colors.orange },
  CmpItemKindFunction = { fg = colors.blue },
  CmpItemKindIdentifier = { fg = colors.red },
  CmpItemKindField = { fg = colors.red },
  CmpItemKindVariable = { fg = colors.magenta },
  CmpItemKindSnippet = { fg = colors.red },
  CmpItemKindText = { fg = colors.base0B },
  CmpItemKindStructure = { fg = colors.magenta },
  CmpItemKindType = { fg = colors.base0A },
  CmpItemKindKeyword = { fg = colors.light.white05 },
  CmpItemKindMethod = { fg = colors.blue },
  CmpItemKindConstructor = { fg = colors.blue },
  CmpItemKindFolder = { fg = colors.light.white05 },
  CmpItemKindModule = { fg = colors.base0A },
  CmpItemKindProperty = { fg = colors.red },
  CmpItemKindUnit = { fg = colors.magenta },
  CmpItemKindFile = { fg = colors.light.white05 },
  CmpItemKindColor = { fg = colors.red },
  CmpItemKindReference = { fg = colors.dark.black20 },
  CmpItemKindStruct = { fg = colors.magenta },
  CmpItemKindOperator = { fg = colors.dark.black20 },
  CmpItemKindTypeParameter = { fg = colors.orange },
  CmpItemKindCopilot = { fg = colors.green },
}
