#!/usr/bin/env bash

export GREEN='\033[1;32m'
export RED='\033[1;31m'
export YELLOW='\033[1;33m'
export NC='\033[0m'

_prompt() {
	local message="$1"
	local variable="$2"

	echo -e "$message"
	read -r "${variable?}"
}

git_info() {
	if [[ "$USER" == "nixos" ]] || [[ "$USER" == "root" ]]; then
		_prompt "${YELLOW}You're running as $USER. Please enter your desired username: ${NC}" USER
	fi

	# Check if git is available
	if command -v git >/dev/null 2>&1; then
		# Fetch email and name from git config
		GIT_EMAIL=$(git config --get user.email)
		export GIT_EMAIL
		GIT_NAME=$(git config --get user.name)
		export GIT_NAME
	else
		echo -e "${RED}Git is not available on this system.${NC}"
	fi

	# If git email is not found or git is not available, ask the user
	if [[ -z "$GIT_EMAIL" ]]; then
		_prompt "${YELLOW}Please enter your email: ${NC}" GIT_EMAIL
	fi

	# If git name is not found or git is not available, ask the user
	if [[ -z "$GIT_NAME" ]]; then
		_prompt "${YELLOW}Please enter your name: ${NC}" GIT_NAME
	fi

	_prompt "${YELLOW}Please enter your Github username: ${NC}" GITHUB_USER
	_prompt "${YELLOW}Please enter your Github secrets repository name: ${NC}" GITHUB_SECRETS_REPO

	export GITHUB_USER
	export GITHUB_SECRETS_REPO
}

confirm_details() {
	echo -e "${GREEN}Username: $USER"
	echo -e "Email: $GIT_EMAIL"
	echo -e "Name: $GIT_NAME${NC}"

	if [[ "$OS" != "Darwin" ]]; then
		echo -e "${GREEN}Primary interface: $PRIMARY_IFACE"
		echo -e "Boot disk: $BOOT_DISK"
		echo -e "Hostname: $HOST_NAME${NC}"
	fi

	echo -e "${GREEN}Secrets repository: $GITHUB_USER/$GITHUB_SECRETS_REPO${NC}"

	_prompt "${YELLOW}Is this correct? (Yes/No): ${NC}" choice
	choice="${choice:-yes}"

	case "$choice" in
	[Nn] | [Nn][Oo])
		echo -e "${RED}Exiting script.${NC}"
		exit 1
		;;
	[Yy] | [Yy][Ee][Ss])
		echo -e "${GREEN}Continuing...${NC}"
		;;
	*)
		echo -e "${RED}Invalid option. Exiting script.${NC}"
		exit 1
		;;
	esac
}

git_info
confirm_details

insert_secrets_input
insert_secrets_output

export -f replace_tokens
find . -type f -exec bash -c 'replace_tokens "$0"' {} \;

echo -e "$USER" >/tmp/username.txt
echo -e "${GREEN}User $USER information applied.${NC}"
