#!/usr/bin/env bash

source ./stdio.sh

FLAKE="macos"

echo -e "${YELLOW}Available generations:${NC}"
/run/current-system/sw/bin/darwin-rebuild --list-generations

echo -e "${YELLOW}Enter the generation number for rollback:${NC}"
read -r GEN_NUM

if [ -z "$GEN_NUM" ]; then
	echo -e "${RED}No generation number entered. Aborting rollback.${NC}"
	exit 1
fi

echo -e "${YELLOW}Rolling back to generation $GEN_NUM...${NC}"
/run/current-system/sw/bin/darwin-rebuild switch --flake .#$FLAKE --switch-generation "$GEN_NUM"

echo -e "${GREEN}Rollback to generation $GEN_NUM complete!${NC}"
