[devshell]
name = "nix-config"
interactive."nix-config".text = "./ssh.sh"

[[commands]]
help = "global linter and formatter orchestrator"
package = "treefmt"
category = "tooling"

[[commands]]
help = "formatter for nix files"
package = "nixpkgs-fmt"
category = "tooling"

[[commands]]
help = "formatter for {ba,da}sh scripts"
package = "shfmt"
category = "tooling"

[[commands]]
help = "formatter for lua scripts"
package = "stylua"
category = "tooling"

[[commands]]
package = "git"
category = "bootstrap"

[[commands]]
package = "nix"
category = "bootstrap"

[[commands]]
package = "home-manager"
category = "bootstrap"

[[env]]
name = "NIX_CONFIG"
value = "experimental-features = nix-command flakes"
